{
 "title": "App Overview",
 "tags": [
  "devops",
  "fastapi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{method}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "Latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, handler))",
     "legendFormat": "p95 {{handler}}"
    }
   ]
  },
  {
   "title": "Errors 5xx (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (handler)",
     "legendFormat": "5xx {{handler}}"
    }
   ]
  },
  {
   "title": "Backend Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend\"}",
     "legendFormat": "RSS"
    }
   ]
  }
 ]
}